using System.Collections;

using System.Collections.Generic;

using UnityEngine;

using UnityEngine.UI;



public class ScoreCode : MonoBehaviour

{
  


    //脓iだ计把计

    public static int Score;
    private static int currScore;
    private static int finalScore;
    //脓iゅrUI

    public Text ShowScore;

    void Start()
    {
        
         Score = 0;
         
    }

    void Update()

    {

        //琵UIゅrPだ计PB

        ShowScore.text = Score.ToString();

       

    }
    

    public int CurrScore
    {
            

        get
        {
            return currScore;
        }


    }

}